dependencies:
  - pip:
      - azureml-sdk
      - azureml-widgets
      - tensorflow-gpu==2.0.0
      - keras<=2.3.1
      - matplotlib
      - pandas
      - numpy
  - python=3.6.2
name: train-covid-keras-tf
